[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "test document project"
authors = [{name = "jane done", email = "janedoe@example"}]
dynamic = ["version", "description"]
